### ISSUE TITLE
Edwin portfolio Project

### ISSUE THREAD

**Issue by egichuhis** [egichuhis/Edwin-Portfolio#16]
Hello, 

I am repeating this module. I have already completed these sections. Feel free to check my project.

Cheers!

**Comment by Eternalgratis** [comment]
Hi @egichuhis Kindly open a PR for this project not an issue in order to review it properly

**Comment by leonardodiasb** [comment]
# Status: ✔️ Project Approved ✔️ 

Hi @egichuhis,

Since you are repeating a module, and the [Pull Request of this exercise](https://github.com/egichuhis/Edwin-Portfolio/pull/2) was previously approved and merged, you are ready to go to the next exercise! :shipit:
Congratulations! 🎉

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
